language: node_js
node_js:
  - "10"

dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

install:
    - npm install

script:
  - npm run build